export const FETCH_START_DAILY_FEED = 'FETCH_START_DAILY_FEED';
export const FETCH_FAIL = 'FETCH_FAIL';
export const FETCH_DAILY_FEED = 'FETCH_DAILY_FEED';
export const FETCH_START_TEMPLATE_FEED = 'FETCH_START_TEMPLATE_FEED';
export const FETCH_TEMPLATE_FEED = 'FETCH_TEMPLATE_FEED';
export const CLEAR_DAILY_FEED = 'CLEAR_DAILY_FEED';
export const SET_NEXT_FEED = 'SET_NEXT_FEED';
export const FETCH_MANY_FEED = 'FETCH_MANY_FEED';
